name = "sukima-api"
main = "src/index.ts"
compatibility_date = "2026-01-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sukima-db"
database_id = "local"
migrations_dir = "migrations"

[vars]
APP_URL = "http://localhost:5173"

# Production environment
[env.production]
name = "sukima-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "sukima-db"
database_id = "16343152-8221-4e17-a181-323308c5a484"
migrations_dir = "migrations"

[env.production.vars]
APP_URL = "https://sukima-app.pages.dev"

[observability]
enabled = true
head_sampling_rate = 1
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
